language: java

jdk:
  - oraclejdk8

script:
  - mvn clean install

after_success:
  - mvn deploy -q --settings settings.xml

notifications:
  email:
  - herve.tchepannou@gmail.com

deploy:
  provider: releases
  user: "$USER_ID"
  password: "$USER_PWD"
  file: target/
  skip_cleanup: true
  on:
    tags: true
